maintainer        "Cloudant"
maintainer_email  "support@cloudant.com"
license           "Apache 2.0"
description       "Configures bigcouch"
version           "0.4.10"
long_description  "Configures bigcouch"
#depends "libicu42"
#depends "libmozjs_1.9.2"
depends "libicu"
depends "spidermonkey"
depends "runit"
depends "libcurl"
depends "bluepill"
